// <auto-generated />
using System;
using FishingTrips.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FishingTrips.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FishingTrips.Api.Models.Angler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Anglers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ivan@example.com",
                            FullName = "Іван Петренко",
                            Level = 1,
                            Phone = "+380501112233",
                            RegisteredAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Email = "olena@example.com",
                            FullName = "Олена Коваль",
                            Level = 0,
                            Phone = "+380672223344",
                            RegisteredAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Email = "sergii@example.com",
                            FullName = "Сергій Мороз",
                            Level = 2,
                            Phone = "+380933334455",
                            RegisteredAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FishingTrips.Api.Models.FishingTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuideId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerPerson")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaterbodyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuideId");

                    b.HasIndex("WaterbodyId");

                    b.ToTable("FishingTrips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndAt = new DateTime(2026, 1, 31, 8, 0, 0, 0, DateTimeKind.Utc),
                            GuideId = 1,
                            MaxParticipants = 4,
                            PricePerPerson = 1200m,
                            StartAt = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            WaterbodyId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndAt = new DateTime(2026, 2, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            GuideId = 2,
                            MaxParticipants = 3,
                            PricePerPerson = 1500m,
                            StartAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            WaterbodyId = 2
                        });
                });

            modelBuilder.Entity("FishingTrips.Api.Models.Guide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("Guides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Спеціалізація — щука, судак.",
                            FullName = "Микола Гнатюк",
                            LicenseNumber = "UA-FG-001",
                            YearsExperience = 12
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Спінінг, сом, нічна рибалка.",
                            FullName = "Андрій Шевчук",
                            LicenseNumber = "UA-FG-002",
                            YearsExperience = 7
                        });
                });

            modelBuilder.Entity("FishingTrips.Api.Models.TripParticipant", b =>
                {
                    b.Property<int>("AnglerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FishingTripId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attended")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CatchWeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("AnglerId", "FishingTripId");

                    b.HasIndex("FishingTripId");

                    b.ToTable("TripParticipants");

                    b.HasData(
                        new
                        {
                            AnglerId = 1,
                            FishingTripId = 1,
                            Attended = false,
                            BookedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            AnglerId = 2,
                            FishingTripId = 1,
                            Attended = false,
                            BookedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FishingTrips.Api.Models.Waterbody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AreaHa")
                        .HasColumnType("REAL");

                    b.Property<string>("FishSpecies")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Waterbodies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaHa = 92200.0,
                            FishSpecies = "щука, судак, лящ, плітка",
                            Location = "Київська обл.",
                            Name = "Київське водосховище",
                            Type = 3
                        },
                        new
                        {
                            Id = 2,
                            AreaHa = 2750.0,
                            FishSpecies = "щука, окунь, лин",
                            Location = "Волинська обл.",
                            Name = "Озеро Світязь",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            AreaHa = 1500.0,
                            FishSpecies = "сом, судак, голавль",
                            Location = "Чернігівська обл.",
                            Name = "Річка Десна",
                            Type = 1
                        });
                });

            modelBuilder.Entity("FishingTrips.Api.Models.FishingTrip", b =>
                {
                    b.HasOne("FishingTrips.Api.Models.Guide", "Guide")
                        .WithMany("LedTrips")
                        .HasForeignKey("GuideId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FishingTrips.Api.Models.Waterbody", "Waterbody")
                        .WithMany("Trips")
                        .HasForeignKey("WaterbodyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guide");

                    b.Navigation("Waterbody");
                });

            modelBuilder.Entity("FishingTrips.Api.Models.TripParticipant", b =>
                {
                    b.HasOne("FishingTrips.Api.Models.Angler", "Angler")
                        .WithMany("Participations")
                        .HasForeignKey("AnglerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FishingTrips.Api.Models.FishingTrip", "FishingTrip")
                        .WithMany("Participants")
                        .HasForeignKey("FishingTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Angler");

                    b.Navigation("FishingTrip");
                });

            modelBuilder.Entity("FishingTrips.Api.Models.Angler", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("FishingTrips.Api.Models.FishingTrip", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("FishingTrips.Api.Models.Guide", b =>
                {
                    b.Navigation("LedTrips");
                });

            modelBuilder.Entity("FishingTrips.Api.Models.Waterbody", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
